In [1]:
import numpy as np

In [12]:
x = np.array([1, '2', 3])

In [13]:
print(x)

['1' '2' '3']


In [14]:
x = [1, 'pedro', 3]

In [15]:
print(x)

[1, 'pedro', 3]


In [16]:
x.append(2)

In [17]:
x

[1, 'pedro', 3, 2]

In [18]:
x

[1, 'pedro', 3, 2]

In [23]:
x = [1, 2, 3]

In [24]:
print(x)

[1, 2, 3]


In [25]:
y = [1, 2, 3]

In [26]:
y

[1, 2, 3]

In [27]:
x+y

[1, 2, 3, 1, 2, 3]

In [28]:
x = np.array([1, 2, 3])

In [29]:
y = np.array([1, 2, 3])

In [30]:
x+y

array([2, 4, 6])

In [31]:
x = np.zeros((5))

In [32]:
x

array([0., 0., 0., 0., 0.])

In [33]:
x = np.ones((5))

In [34]:
x

array([1., 1., 1., 1., 1.])

In [35]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
x[2:6]

array([3, 4, 5, 6])

In [38]:
x[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [39]:
x[:2]

array([1, 2])

In [41]:
x = np.array([[1, 2, 3], [1, 2, 3]])

In [42]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [46]:
x[1][2]

3

In [47]:
x = np.array([1, 2, 3, 4, 5]*5)

In [48]:
x

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [49]:
print(x)

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [57]:
for i in x:
    print(i, end=' ')

1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 

In [58]:
x

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [59]:
x = np.array([1, 2, 3]*3)

In [60]:
x

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [61]:
x = np.array([[1, 2, 3]]*3)

In [62]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [63]:
x = np.array([[1, 2, 3, 4, 5]]*5)

In [64]:
x

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [65]:
x = np.array([range(5)]*5)

In [66]:
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [67]:
x = np.zeros((5, 5))

In [68]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
x = np.eye((5))

In [70]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
x = np.arange(5)

In [73]:
x

array([0, 1, 2, 3, 4])

In [74]:
x = np.array(range(5))

In [75]:
x

array([0, 1, 2, 3, 4])