In [1]:
import numpy as np

In [2]:
#adicao de matrizes

In [7]:
x = np.array([range(3)]*3)
x

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
y = np.array([range(3, 6)]*3)
y

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [10]:
soma = x+y
soma

array([[3, 5, 7],
       [3, 5, 7],
       [3, 5, 7]])

In [11]:
sub = y-x
sub

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])