In [1]:
import numpy as np

In [2]:
x = np.array([range(5)]*5)

In [3]:
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [4]:
y = np.array([range(5, 10)]*5)

In [5]:
y

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [6]:
x+y

array([[ 5,  7,  9, 11, 13],
       [ 5,  7,  9, 11, 13],
       [ 5,  7,  9, 11, 13],
       [ 5,  7,  9, 11, 13],
       [ 5,  7,  9, 11, 13]])